version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5501:5501"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5501
      - ConnectionStrings__DefaultConnection=localhost,1433;Database=AppDbName;User Id=sa;Password=MyPassword1234;Encrypt=false;MultipleActiveResultSets=true
    depends_on:
      - db
    networks:
      - levenue-network
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - levenue-network
    restart: unless-stopped

volumes:
  sqldata:
    driver: local

networks:
  levenue-network:
    driver: bridge